sudo: required

language: java

jdk:
- oraclejdk8

services:
  - docker

before_install:
  - docker-compose -f docker/docker-compose.yml up
  
addons:
  sauce_connect:
    username: graylog
    access_key:
      secure: rdAfGo7BShMiWPwOBhMA5c3zpg/wgAnI0PTx1/bFL9ZSXTSCgO6JkQnIW096LypvI1u9kgh98I2pA+5hmZHhJVtnZNgwdZaGXrT7x6viILVPZ2bOkssr0MmOk1vPcadzWyB4xNjABkz9d8QLhMds7qZM4XWdaUd9LDXCIe+Ex9roLAiPWvBOUDHVQu3JmSG49hZdCIPxTjQMft9ZwtSG8PTogpJEH9MwKASL5CWznXE1qVAyBdmJ7Dp6iO60jogz5iyD8mcY+VAH+yZScBWpisB+C5HpOq2knUkh9ZQ5dQF8z2350nEjZX1SvjNBhYpCNcUbcPMzLCW51Tav4rPiZcyGlo50TUOaKCRu26YrrWHNqAfd9qbgOv4OqG9LuAHgK8z8IKMCm33jMNNgUd0pEkpIFFL/IeDFNzVOETWCFd+N82LvPSzrmyvuZDnHXwf9ZBE5QRgCsmCXWpkNbNL1lXiVOX3+uXwknNO46L3WcxKxEQjU9iW6elJzuAjcoWf4P48GjGF5KzWTt3xt36yJZvlxQDLl7mDWLBhSpyrF0Swc925Xhdpo640TKYn1KIpku4z/0rx0bj5kuC4Kzhy0bIOUvyE4dht9FeTjYd5afVOzS/uMrRY+biAeVsQU/BhSxGsx0x/sKmW/TCPdZGYPadiPANHE3w0vMS8/PFXOS3w=

env:
  SAUCE_USERNAME: graylog
  global:
    secure: hTuMZwJkd0fKoiEAsY4uvmHhsWKrzkBCDSNiwvOndpr500HrzgUfsJ+D5mU7eVfFomlBdEubB8Ubkn5n/ozSW0BukcuEb6O7l8AN3ixjubjC8zQBijpVrVHpYPA8aMkD12K+jhOTnzbVROq3PcFjwSgLkBF8ENN+JZvTTSyvEfwGYEEcZozPdware6lyJx7fk9jpk8JecAnYNgSt3cbWcoESxLnoO69ZDtEFut5QTM0+pqxjGHzoo83C2vUe8MtSwzisGQsA9ktq4yffYeJYNM00fOq7By8bB79E24MeUUjA9ZPREzoI6ZXX3wlqXZbU0qi8c0W2MdGIbDdkRIteZRkCk0x9aEacRJKJMtYx4/H+B/T3QSb0Vh5gzmHbL3SCK6KPj77gcfRMeh8iOv32ZDe6SFVwL5jh8Wg+78zwXA3jaRsu2pKLQ7gXT3/SCNiizaLxXIIcYixHmt74MTHI3+SPP4L273z/tHQhKoTmjhla89Njie7oQ/xOBNfTPC7dGCyaBk2FT7qJZidK1CjEnWJzPI/RmzQ3y/s5Y2ekuvvm8Z2zqzwe2e+9FvIgEXvfNF7hatYTt5IbjEy0hBwVi2m11KW9xPhW6NHK1P9KApHRA0fH0y4CHcGj1R/U2+K/ddmrAuojMJ+oKUITmiuUx25ah3URhA6YmO6hZfFYffk=
